language: python

python:
  - 3.6

before_install:
  - sudo add-apt-repository ppa:gstreamer-developers/ppa -y
  - sudo apt-get update
  - sudo apt-get install -y gstreamer1.0*

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - cd pygallerycreator 
  - python -m pytest --cov=.
  

after_success:
  coveralls

branches:
  only:
    - master